### ISSUE TITLE
Conflict with other Jquery libary

### ISSUE THREAD

**Issue by sailor80** [optikalefx/OpenJS-Grid#61]
Hey Sean. 
First thanks a lot for great video and scripts. 

I am a kind newbie and are makeing my first project and wants to use OpenJS Grid to collect values into. 
But i have a problem with a conflict with a other Jquery libarary.. 
when i use the same file then it dont work 
but if i hide this line: 
  <!--  <script src="../bower_components/jquery/dist/jquery.min.js"></script> 

then OpenJS grid works fine but my menu dosent. 

Do you have a suggestion how to solve this problem ?

Best Regards

**Comment by optikalefx** [comment]
Can you give me some more detail. What line? What plugins are you using?
