### ISSUE TITLE
small showNumRows breaks the table

### ISSUE THREAD

**Issue by wellumies** [optikalefx/OpenJS-Grid#64]
go to http://samui.kipase.com/index3.php with Firefox 36.0.1

showNumRows is 5 and the Total column drops under the table

**Comment by wellumies** [comment]
also breaks in Chrome 40.0.2214.115 m

**Comment by optikalefx** [comment]
I haven't used this many columns before, will need to check this out

**Comment by wellumies** [comment]
Still haven't figured out why the max visible rows is always 7? No matter what showNumRows you use. It is a pain to scroll in an iPhone when the scrollbar is also bugged. Right side of the scrollbar is not selectable

**Comment by optikalefx** [comment]
the max nRowsShowing is the number actual rows to send to the browser. The problem you're seeing (which is not the subject of this ticket) is the CSS height of the grid.  Changing the nRowsShowing just changes the number of data rows sent, not the rows visible to the user, to adjust the height of the grid use css
