### ISSUE TITLE
Export functions?

### ISSUE THREAD

**Issue by MGA555** [optikalefx/OpenJS-Grid#66]
Are export functions provided?  These are critical for me, and the YouTube video discussing version 1.8 indicated they were coming.  I have looked all over and found no mention of export functions.  I am a newbie here, so if I am overlooking something, I apologize..

**Comment by optikalefx** [comment]
Alas, I have not had a chance to build these into the grid. I've made exporters for projects and just added a button the grid.  So for now, there is no automatic exporting, you'd have to make an export and give your grid a button to download that export.

**Comment by MGA555** [comment]
Thanks for such a quick response.  I wish my paid dedicated server vendor responded anywhere close to yours.

Would you be willing to send/post an export example you are proud of, one that might be used as the basis for your eventual inclusion in OpenJS Grid, which by the way looks like an excellent and profound resource.

Also, I wonder if this is the right place for this, or is there some kind of OpenJS Grid chat resource?

thanks again

**Comment by optikalefx** [comment]
This is probably a good place. We can mark it as a feature request.  Honestly my exports are just a raw SQL query that writes to a CSV. All of that in 1 ajax call, and then the button just calls the ajax and redirects the browser to the new CSV file. Not really any magic going on there.

Thanks, the Open Source community is generally more responsive for active projects.
