### ISSUE TITLE
CSS Conflicts

### ISSUE THREAD

**Issue by MGA555** [optikalefx/OpenJS-Grid#68]
I have finally gotten to install an almost useful implementation of OpenJS Grid in a website of mine.  I am at the point where the table shows up, but I have a number of CSS conflicts between the site and OpenJS Grid.  I wonder if this is inevitable, of if perhaps I made a simple implementation error.  The kinds of conflicts I am having to work around are 1) a left column series of vertical navigation buttons end up will bullets added to them, 2) the width of my page has changed, and 3) the CSS for the "paging" menu at the bottom of the table is all messed up.

I'm sure I can hack my way through all of these, but do not like the prospect of having to do that every time I add a grid to an existing page.

Any suggestions/insight?

**Comment by MGA555** [comment]
It looks like all of my CSS issues were resolvable by placing the OpenJS Grid CSS before the pre-existing CSS statements on the webpage.  I had originally place them after.from habit.

I tried changing the order because I understood that the OpneJS Grid CSS would take precedence over my ore-existing CSS if the OpenJS Grid CSS statements were added after the pre-existing ones, and that could change the styling of any elements that shared ID, Class or other identification with my pre-existing page elements. .

I did however, expect that giving my pre-existing CSS precedence would mess up some of the OpenJS Grid CSS, but at least so far that has not happened.  I find that quite confusing, since I assume some of the page elements must have the identification as OpenJS Grid elements.  Perhaps there will be no conflicts in the future, or perhaps I will get some as I use additional OpenJS Grid features.

**Comment by optikalefx** [comment]
Crazy, yea I tried to keep all my OpenJS grid styles isolated.  Which means it should come first, and then other custom styles after. Though it shouldn't matter either way, it's odd that it does.  It is heavily based on bootstrap 2 themes. So there's that.
