### ISSUE TITLE
Revision 3.0?

### ISSUE THREAD

**Issue by MGA555** [optikalefx/OpenJS-Grid#71]

**Comment by MGA555** [comment]
Any notion of the schedule for Revision 3.0?

thanks

**Comment by optikalefx** [comment]
Not yet, day job is keeping me very busy. I'll post when I've got a timeline though.  I still use v2 for a lot of projects.

**Comment by MGA555** [comment]
Understood.  The feature in 3.0 that I really look forward to is including an export.  That and adding a row are the two things that (at least for my purposes) prevent OpenJS Grid from living up to its declared goals.

I am enjoying using this package, and learning more about it.  Thanks for the effort you have expended to get this out there.
