### ISSUE TITLE
Drop downs, more than one

### ISSUE THREAD

**Issue by jdamianb** [optikalefx/OpenJS-Grid#77]
Hello,

I have a doubt. How can I use 2 or more drop downs that reads info from a mysql database.

Thank you,

**Comment by optikalefx** [comment]
From the drop down example on this page http://square-bracket.com/openjs you can just specify as many `$selects["{{FIELD}}"]` as needed

**Comment by jdamianb** [comment]
But if I want data from another table on the same db what should I do?

**Comment by optikalefx** [comment]
as seen on that example page, just call `$grid->table = "categories";` before you make your `$grid->makeSelect` That will tell makeSelect to use a different table

**Comment by jdamianb** [comment]
But what about two different tables for two different drop downs?

**Comment by optikalefx** [comment]
```
$grid->table = "categories";
$selects["CategoryID"] = $grid->makeSelect("CategoryID","Name");

$grid->table = "another_table";
$selects["active"] = array("1"=>"true","0"=>"false");

$grid->table = "another_another_table";
$selects["aNewColumn"] = $grid->makeSelect("CategoryID","Name");
```

**Comment by jdamianb** [comment]
Hi! I did that but now I know why it wasn't working. The problem I have is that I'm using spanish words with special characters lik "á", so that's why it wasn't loading the drop downs. I have posted my problem on another issue. I hope you can help me there.

Thank you!
