### ISSUE TITLE
Grid class pass query instead of tablename

### ISSUE THREAD

**Issue by ghost** [optikalefx/OpenJS-Grid#95]
Hi,
This is not a bug its a request that i should able to pass query direct instead of table. Because when you need to create dynamic tables its easy to just pass the query and let the class do all instead of passing join array and where array and field array etc. Plus its more efficient as u don't need to reconstruct the query as you do currently by adding joints and group by etc instead just fire the query and get results.In this case you will need to reconstruct the where clause thats it rest can be directly achieve from query passed.

This is my suggestion and i myself working on it rest you know better than me.
Thanks in advance

**Comment by optikalefx** [comment]
The problem with this method, is that searching, sorting and paging is done server side. Therefore I need to break the query up into parts in order to add paging, sorting and searching to the query. If you give me any query, the parsing becomes inaccurate and much harder to solve.

**Comment by ghost** [comment]
hmm yaa you are right. But i already achieved some what of this by creating following alternate method

//
function load2($sql) {
        $post = $this->_safeMysql();

```
    // setup variables from properties

    $where = $this->where;

    // we need to break this up for use
    $colsArray = explode(",",$post['cols']);


    // get an array of saveable fields
    $saveable = $colsArray;
    // bug #1# @eric.tuvesson@gmail.com

    $order_by = isset($post['orderBy']) ? $post['orderBy'] : $colsArray[0];

    // save variables for easier use throughout the code
    $sort = isset($post['sort']) ? $post['sort'] : "asc";
    $nRowsShowing = isset($post['nRowsShowing']) ? $post['nRowsShowing'] : 10;
    $page = isset($post['page']) ? $post['page'] : 1;


    $startRow = ($page - 1) * $nRowsShowing;

    // bring all the joins togther if sent


    $post['cols'] = implode(",",$colsArray);




    // specific where setup for searching
    if(isset($post['search']) && $post['search']) {
        // if there is a search term, add the custom where first, then the search
        $where = !$where ? " WHERE " : " WHERE ($where) && ";
        // if you are searching, at a like to all the columns
        $where .= "(".implode(" LIKE '%$post[search]%' || ",$colsArray) . " LIKE '%$post[search]%')";
    } else {
        // add the where keyword if there is no search term
        if($where) {
            $where = "WHERE $where";
        }
    }



    if($startRow < 0) $startRow = 1;

    // we need this seperate so we can not have a limit at all
    $limit = "LIMIT $startRow,$nRowsShowing";

    // if were searching, see if we want all results or not
    if(isset($_POST['pager']) && $_POST['pager'] == "false" || (!empty($_POST['search']) && i     isset($_POST['pageSearchResults']))) {
        $limit = "";
    }

    $order = strpos($order_by,".") === false ? "`$order_by`" : $order_by;
    $groupBy = $this->groupBy ? "GROUP BY ".$this->groupBy : "";
    $having = $this->having ? "HAVING ".$this->having : "";

    $sql =$sql." 
        $where
        $groupBy
        $having
        ORDER BY $order $sort
        $limit";



    $this->sql = $sql;

    // execute the sql, get back a multi dimensial array
    $rows = $this->_queryMulti($sql);

    // die with messages if fail
    $this->dieOnError($sql);


    // form an array of the data to send back
    $data = array();
    $data['rows'] = array();
    foreach($rows as $i=>$row) {
        foreach($row as $col=>$cell) {
            // use primary key if possible, other wise use index
            $key = $i;

            // primary key has an _ infront becuase of google chrome re ordering JSON objects
            //http://code.google.com/p/v8/issues/detail?id=164
            $data['rows']["_".$key][$col] = utf8_encode($cell);
        }
    }

    // if were searching and we dont want all the results - dont run a 2nd query
    if(isset($_POST['pager']) && $_POST['pager'] == "false" || (!empty($_POST['search']) && isset($_POST['pageSearchResults']))) {
        $data['nRows'] = count($rows);
        $startRow = 0;
        $nRowsShowing = $data['nRows'];
    } else {
        if(!$this->limit) {
            // use the same query for counting less the limit
            $sql2 = preg_replace('/LIMIT[\s\d,]+$/','',$sql);

            // find the total results to send back
            $res = mysql_query($sql2);
            $data['nRows'] = mysql_num_rows($res);
        } else {
            $data['nRows'] = $this->limit;
        }
    }
    $colData = array();

    $data['order_by'] = $order_by;
    $data['sort'] = $sort;
    $data['page'] = $page;
    $data['start'] = $startRow + 1;
    $data['end'] = $startRow + $nRowsShowing;
    $data['colData'] = $colData;    
    $data['saveable'] = $saveable;
    $this->data = $data;

    return $this;
} 
```

But yaa i havent changed much in this just remove joins requirement but lets see i can change more. I am also trying to remove the need of creating table as well and retrieving column name from query itself and set width and everything automatically.

But currently i managed to dynamically create table.

for that i created this methods 

//

function getcolumns($sql,$tablename)
{
$sql=$sql." LIMIT 1 OFFSET 0";
$query=$this->db->query($sql);
$columns= $query->list_fields();
return $columns;
}
    function generatecolumns($tablename,$columnname,$page)
    {
        $title=array();
        for ($i = 0; $i <sizeof($columnname); $i++)
        {
            $newstring=str_replace("_"," ",$columnname[$i]);

```
        $title[$i]=ucwords(ltrim($newstring));
    }
    return $this->generatetable($tablename,$columnname,$title,null,$page);
}
```

function generatetable($tablename,$columnname,$title,$width,$page)
    {
        $table="<table class='grid users' action='/ACM/grid/".$page."'>";
        $table.="<tr>";
        for ($i = 0; $i <sizeof($columnname); $i++)
        {
            if ((strpos($columnname[$i], 'id') == true)&&($i==0))
            {

```
        }

        else
        {
            $table .="<th col='".$columnname[$i]."' >".$title[$i]."</th>";
        }
    }
    $table .="</tr></table>";

    return $table;

}
```

//

Show i pass query and tablename to getcolumns method and then by other two methods i get columnname, Alias name and dynamically create table. then passing same query get grid as well.

So makes life little easy. What you say
