### ISSUE TITLE
I am trying to achieve group view functionality as shown in picture can u help in that. Thanks in advance

### ISSUE THREAD

**Issue by ghost** [optikalefx/OpenJS-Grid#97]
![grouping](https://cloud.githubusercontent.com/assets/5344324/17551943/84d36194-5f1a-11e6-8d7e-8cd8e1d6f19b.png)

**Comment by optikalefx** [comment]
That isn't built into the grid. And would be pretty complex to add actually. The way I handle this master-child grids. But unfortunately if you want to do groupings you're won't e able to use this.

**Comment by ghost** [comment]
hmm ok i will try my luck if works will post you
